version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-service
    ports:
      - "11435:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: /tmp/run_ollama.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spam-detection-app
    ports:
      - "8501:8501"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped

volumes:
  ollama-data: 