FROM ollama/ollama

# Install curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY ./run_ollama.sh /tmp/run_ollama.sh
COPY configs/model/model.yaml /tmp/model.yaml

WORKDIR /tmp

# Make script executable during build
RUN chmod +x /tmp/run_ollama.sh

EXPOSE 11434 

# Add entrypoint to pull the model and start ollama
ENTRYPOINT ["/tmp/run_ollama.sh"] 